### ISSUE TITLE
Unsupported file type

### ISSUE THREAD

**Issue by ShawnTheBeachy** [Microsoft/groove-api-sdk-csharp#7] opened 2017-02-21 06:16 UTC
When signed in, it's impossible to play songs. It just says it's an "unsupported file type". I've tested on two separate machines, using both this app and my own testing app.

**Comment by bfreydier** [comment] 2017-02-21 13:35
Hi and thanks for reporting this.

We've identified an issue on HLS stream consumption with MediaSource on some versions of Windows. The sample app code has been updated to use an AdaptiveMediaSource (the root cause was a User-Agent header mismatch between HLS manifest & fragment request).

This fix is merged and part of the following PR: #8

**Closed as completed** 2017-02-21 13:38 UTC
